### PR TITLE
Fix compilation error on gcc13.

### PR DESCRIPTION
**Pull request by mx**
Requires cstdint to be explicitly included where types like uint8_t are used.

### CODE REVIEW

**Comment by SteveRussell33** [comment]
No error rebuilding on Windows using GCC v13.1.0

**Comment by mx** [comment]
Admittedly I didn't look on Windows. Head does fail on Linux though; this PR fixes that.

**Comment by cosinekitty** [comment]
@mx Thanks for the PR. I appreciate the problem report and the fix. But it reformats my code to a different coding style. Is adding the single `#include` all that is needed?

**Comment by mx** [comment]
@cosinekitty Oops, I didn't turn off clang-format, sorry about that...yes, the single include is all that's needed.

**Comment by mx** [comment]
There we go, fixed the PR :-)

**Comment by cosinekitty** [comment]
Thank you so much for reporting this and fixing it!

**Pull request merged**
